In [3]:
import pandas as pd
import numpy as np

data_frame= pd.read_csv("empleados_technova_sucio.csv")

data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             18 non-null     int64
 1   nombre         18 non-null     str
 2   edad           15 non-null     float64
 3   ciudad         18 non-null     str
 4   departamento   18 non-null     str
 5   salario        18 non-null     str
 6   fecha_ingreso  18 non-null     str
 7   correo         16 non-null     str
dtypes: float64(1), int64(1), str(6)
memory usage: 1.3 KB

In [4]:
display(data_frame)

,id,nombre,edad,ciudad,departamento,salario,fecha_ingreso,correo
0,1,Ana Pérez,34.0,Santiago,Ventas,$850.000,2020-03-15,ana.perez@technova.cl
1,2,Carlos Soto,28.0,santiago,ventas,$1.200.000,2019-07-01,carlos.soto@technova.cl
2,3,María González,NaN,SANTIAGO,Marketing,$950.000,2021-01-20,maria.gonzalez@technova.cl
3,4,Pedro Ramírez,45.0,Valparaíso,VENTAS,1500000,2018-11-05,NaN
4,5,Lucía Fernández,999.0,valparaíso,marketing,$1.100.000,2022-05-12,lucia.fernandez@technova.cl
5,6,José Muñoz,NaN,Concepción,Soporte,$780.000,2020-09-30,jose.munoz@technova.cl
6,7,Carla Díaz,31.0,concepción,soporte,$820.000,2021-03-08,-
7,8,Roberto Rojas,52.0,Antofagasta,Gerencia,$2.500.000,2017-02-14,roberto.rojas@technova.cl
8,9,Fernanda Torres,0.0,Santiago,Marketing,$990.000,2023-06-01,fernanda.torres@technova.cl
9,10,Diego Castro,38.0,santiago,Soporte,?,2019-12-19,diego.castro@technova.cl
10,11,Valentina Silva,29.0,Iquique,Ventas,$880.000,2022-08-23,valentina.silva@technova.cl
11,2,Carlos Soto,28.0,santiago,ventas,$1.200.000,2019-07-01,carlos.soto@technova.cl
12,13,Andrés López,41.0,IQUIQUE,gerencia,$2.300.000,2018-04-17,andres.lopez@technova.cl
13,14,Camila Vargas,NaN,Valparaíso,Soporte,$800.000,2021-10-02,camila.vargas@technova.cl
14,15,Sebastián Reyes,36.0,Concepción,VENTAS,$1.050.000,2020-01-28,NaN
15,16,Javiera Núñez,27.0,santiago,Marketing,$910.000,2023-02-11,javiera.nunez@technova.cl
16,17,Matías Herrera,33.0,Antofagasta,soporte,$830.000,2019-05-09,matias.herrera@technova.cl
17,18,Paula Morales,48.0,antofagasta,Gerencia,$2.400.000,2016-08-21,paula.morales@technova.cl

In [5]:
data_frame["ciudad"].unique() # cuantos valores únicos hay en la columna ciudad?

<StringArray>
[   'Santiago',    'santiago',    'SANTIAGO',  'Valparaíso',  'valparaíso',
  'Concepción',  'concepción', 'Antofagasta',     'Iquique',     'IQUIQUE',
  ' santiago ', 'antofagasta']
Length: 12, dtype: str

In [6]:
data_frame.isna().sum() # cuantos faltantes hay en cada columna?

id               0
nombre           0
edad             3
ciudad           0
departamento     0
salario          0
fecha_ingreso    0
correo           2
dtype: int64

In [7]:
data_frame.isna().head()
data_frame.isna().sum()

id               0
nombre           0
edad             3
ciudad           0
departamento     0
salario          0
fecha_ingreso    0
correo           2
dtype: int64

In [8]:
# Cargar bien desenmascarar los faltante
data_frame = pd.read_csv("empleados_technova_sucio.csv", na_values=["-", "?"])

In [9]:
data_frame.isna().sum()   # ahora deberían aparecer los faltantes correctamente contabilizados

id               0
nombre           0
edad             3
ciudad           0
departamento     0
salario          1
fecha_ingreso    0
correo           3
dtype: int64

In [10]:
# Duplicado 
data_frame.duplicated().sum()  # cuántos registros duplicados hay?

np.int64(1)

In [11]:
data_frame = data_frame.drop_duplicates().reset_index(drop=True)  # eliminar duplicados y resetear índices

In [12]:
len(data_frame)

17

In [13]:
# Quitar espacio al inicio y al final
for col in ["nombre", "ciudad", "departamento"]:
    data_frame[col] = data_frame[col].str.strip()

In [14]:
data_frame.duplicated(subset=["id"]).sum()  # verificar si hay duplicados basados solo en la columna id

np.int64(0)

In [15]:
data_frame[data_frame.duplicated(subset=["id"], keep=False)] # ver las filas que tienen id duplicados para entender mejor el problema

Empty DataFrame
Columns: [id, nombre, edad, ciudad, departamento, salario, fecha_ingreso, correo]
Index: []

In [16]:
data_frame["nombre"] = data_frame["nombre"].str.strip()
data_frame["ciudad"] = data_frame["ciudad"].str.strip()
data_frame["departamento"] = data_frame["departamento"].str.strip()

In [17]:
#data_frame = data_frame.str.strip()

In [18]:
# Detectar automaticamente las columnas de texto
cols_texto = data_frame.select_dtypes(include=["str"]).columns
# aplicar strip a solo esas
data_frame[cols_texto] = data_frame[cols_texto].apply(lambda x: x.str.strip())

In [19]:
display(data_frame)

,id,nombre,edad,ciudad,departamento,salario,fecha_ingreso,correo
0,1,Ana Pérez,34.0,Santiago,Ventas,$850.000,2020-03-15,ana.perez@technova.cl
1,2,Carlos Soto,28.0,santiago,ventas,$1.200.000,2019-07-01,carlos.soto@technova.cl
2,3,María González,NaN,SANTIAGO,Marketing,$950.000,2021-01-20,maria.gonzalez@technova.cl
3,4,Pedro Ramírez,45.0,Valparaíso,VENTAS,1500000,2018-11-05,NaN
4,5,Lucía Fernández,999.0,valparaíso,marketing,$1.100.000,2022-05-12,lucia.fernandez@technova.cl
5,6,José Muñoz,NaN,Concepción,Soporte,$780.000,2020-09-30,jose.munoz@technova.cl
6,7,Carla Díaz,31.0,concepción,soporte,$820.000,2021-03-08,NaN
7,8,Roberto Rojas,52.0,Antofagasta,Gerencia,$2.500.000,2017-02-14,roberto.rojas@technova.cl
8,9,Fernanda Torres,0.0,Santiago,Marketing,$990.000,2023-06-01,fernanda.torres@technova.cl
9,10,Diego Castro,38.0,santiago,Soporte,NaN,2019-12-19,diego.castro@technova.cl
10,11,Valentina Silva,29.0,Iquique,Ventas,$880.000,2022-08-23,valentina.silva@technova.cl
11,13,Andrés López,41.0,IQUIQUE,gerencia,$2.300.000,2018-04-17,andres.lopez@technova.cl
12,14,Camila Vargas,NaN,Valparaíso,Soporte,$800.000,2021-10-02,camila.vargas@technova.cl
13,15,Sebastián Reyes,36.0,Concepción,VENTAS,$1.050.000,2020-01-28,NaN
14,16,Javiera Núñez,27.0,santiago,Marketing,$910.000,2023-02-11,javiera.nunez@technova.cl
15,17,Matías Herrera,33.0,Antofagasta,soporte,$830.000,2019-05-09,matias.herrera@technova.cl
16,18,Paula Morales,48.0,antofagasta,Gerencia,$2.400.000,2016-08-21,paula.morales@technova.cl

In [20]:
data_frame["ciudad"] = data_frame["ciudad"].str.title()  # "santiago" -> "Santiago"
data_frame["departamento"] = data_frame["departamento"].str.capitalize()  # "ventas" -> "Ventas"

In [21]:
data_frame["ciudad"].unique() # cuantos valores únicos hay en la columna ciudad?
data_frame["departamento"].unique() # cuantos valores únicos hay en la columna departamento?

<StringArray>
['Ventas', 'Marketing', 'Soporte', 'Gerencia']
Length: 4, dtype: str

In [23]:
data_frame["salario"] = (data_frame["salario"].str.replace("$","", regex=False)
                                              .str.replace(".","", regex=False)
                                              .astype(float))

In [ ]:
data_frame["salario"].dtype # float64, ahora sí es numérica y se pueden hacer cálculos con ella

dtype('float64')

In [25]:
display(data_frame)

,id,nombre,edad,ciudad,departamento,salario,fecha_ingreso,correo
0,1,Ana Pérez,34.0,Santiago,Ventas,850000.0,2020-03-15,ana.perez@technova.cl
1,2,Carlos Soto,28.0,Santiago,Ventas,1200000.0,2019-07-01,carlos.soto@technova.cl
2,3,María González,NaN,Santiago,Marketing,950000.0,2021-01-20,maria.gonzalez@technova.cl
3,4,Pedro Ramírez,45.0,Valparaíso,Ventas,1500000.0,2018-11-05,NaN
4,5,Lucía Fernández,999.0,Valparaíso,Marketing,1100000.0,2022-05-12,lucia.fernandez@technova.cl
5,6,José Muñoz,NaN,Concepción,Soporte,780000.0,2020-09-30,jose.munoz@technova.cl
6,7,Carla Díaz,31.0,Concepción,Soporte,820000.0,2021-03-08,NaN
7,8,Roberto Rojas,52.0,Antofagasta,Gerencia,2500000.0,2017-02-14,roberto.rojas@technova.cl
8,9,Fernanda Torres,0.0,Santiago,Marketing,990000.0,2023-06-01,fernanda.torres@technova.cl
9,10,Diego Castro,38.0,Santiago,Soporte,NaN,2019-12-19,diego.castro@technova.cl
10,11,Valentina Silva,29.0,Iquique,Ventas,880000.0,2022-08-23,valentina.silva@technova.cl
11,13,Andrés López,41.0,Iquique,Gerencia,2300000.0,2018-04-17,andres.lopez@technova.cl
12,14,Camila Vargas,NaN,Valparaíso,Soporte,800000.0,2021-10-02,camila.vargas@technova.cl
13,15,Sebastián Reyes,36.0,Concepción,Ventas,1050000.0,2020-01-28,NaN
14,16,Javiera Núñez,27.0,Santiago,Marketing,910000.0,2023-02-11,javiera.nunez@technova.cl
15,17,Matías Herrera,33.0,Antofagasta,Soporte,830000.0,2019-05-09,matias.herrera@technova.cl
16,18,Paula Morales,48.0,Antofagasta,Gerencia,2400000.0,2016-08-21,paula.morales@technova.cl

In [27]:
print("edad antes:  ", sorted(data_frame["edad"].dropna().unique().astype(int)))

edad antes:   [np.int64(0), np.int64(27), np.int64(28), np.int64(29), np.int64(31), np.int64(33), np.int64(34), np.int64(36), np.int64(38), np.int64(41), np.int64(45), np.int64(48), np.int64(52), np.int64(999)]

In [28]:
# regla de negocio: edad válida entre 18 y 90
data_frame.loc[(data_frame["edad"] < 18) | (data_frame["edad"] > 90), "edad"] = np.nan

In [30]:
print("edad después:", sorted(data_frame["edad"].dropna().unique().astype(int)))

edad después: [np.int64(27), np.int64(28), np.int64(29), np.int64(31), np.int64(33), np.int64(34), np.int64(36), np.int64(38), np.int64(41), np.int64(45), np.int64(48), np.int64(52)]

In [31]:
display(data_frame)

,id,nombre,edad,ciudad,departamento,salario,fecha_ingreso,correo
0,1,Ana Pérez,34.0,Santiago,Ventas,850000.0,2020-03-15,ana.perez@technova.cl
1,2,Carlos Soto,28.0,Santiago,Ventas,1200000.0,2019-07-01,carlos.soto@technova.cl
2,3,María González,NaN,Santiago,Marketing,950000.0,2021-01-20,maria.gonzalez@technova.cl
3,4,Pedro Ramírez,45.0,Valparaíso,Ventas,1500000.0,2018-11-05,NaN
4,5,Lucía Fernández,NaN,Valparaíso,Marketing,1100000.0,2022-05-12,lucia.fernandez@technova.cl
5,6,José Muñoz,NaN,Concepción,Soporte,780000.0,2020-09-30,jose.munoz@technova.cl
6,7,Carla Díaz,31.0,Concepción,Soporte,820000.0,2021-03-08,NaN
7,8,Roberto Rojas,52.0,Antofagasta,Gerencia,2500000.0,2017-02-14,roberto.rojas@technova.cl
8,9,Fernanda Torres,NaN,Santiago,Marketing,990000.0,2023-06-01,fernanda.torres@technova.cl
9,10,Diego Castro,38.0,Santiago,Soporte,NaN,2019-12-19,diego.castro@technova.cl
10,11,Valentina Silva,29.0,Iquique,Ventas,880000.0,2022-08-23,valentina.silva@technova.cl
11,13,Andrés López,41.0,Iquique,Gerencia,2300000.0,2018-04-17,andres.lopez@technova.cl
12,14,Camila Vargas,NaN,Valparaíso,Soporte,800000.0,2021-10-02,camila.vargas@technova.cl
13,15,Sebastián Reyes,36.0,Concepción,Ventas,1050000.0,2020-01-28,NaN
14,16,Javiera Núñez,27.0,Santiago,Marketing,910000.0,2023-02-11,javiera.nunez@technova.cl
15,17,Matías Herrera,33.0,Antofagasta,Soporte,830000.0,2019-05-09,matias.herrera@technova.cl
16,18,Paula Morales,48.0,Antofagasta,Gerencia,2400000.0,2016-08-21,paula.morales@technova.cl

In [32]:
# Tratar los valores perdidos
# edad -> mediana (numérica y robusta ante atípicos)
data_frame["edad"] = data_frame["edad"].fillna(data_frame["edad"].median()).astype(int)

In [33]:
# salario -> mediana
data_frame["salario"] = data_frame["salario"].fillna(data_frame["salario"].median())

In [35]:
data_frame["correo"] = data_frame["correo"].fillna("sin_correo")

In [36]:
display(data_frame)

,id,nombre,edad,ciudad,departamento,salario,fecha_ingreso,correo
0,1,Ana Pérez,34,Santiago,Ventas,850000.0,2020-03-15,ana.perez@technova.cl
1,2,Carlos Soto,28,Santiago,Ventas,1200000.0,2019-07-01,carlos.soto@technova.cl
2,3,María González,35,Santiago,Marketing,950000.0,2021-01-20,maria.gonzalez@technova.cl
3,4,Pedro Ramírez,45,Valparaíso,Ventas,1500000.0,2018-11-05,sin_correo
4,5,Lucía Fernández,35,Valparaíso,Marketing,1100000.0,2022-05-12,lucia.fernandez@technova.cl
5,6,José Muñoz,35,Concepción,Soporte,780000.0,2020-09-30,jose.munoz@technova.cl
6,7,Carla Díaz,31,Concepción,Soporte,820000.0,2021-03-08,sin_correo
7,8,Roberto Rojas,52,Antofagasta,Gerencia,2500000.0,2017-02-14,roberto.rojas@technova.cl
8,9,Fernanda Torres,35,Santiago,Marketing,990000.0,2023-06-01,fernanda.torres@technova.cl
9,10,Diego Castro,38,Santiago,Soporte,970000.0,2019-12-19,diego.castro@technova.cl
10,11,Valentina Silva,29,Iquique,Ventas,880000.0,2022-08-23,valentina.silva@technova.cl
11,13,Andrés López,41,Iquique,Gerencia,2300000.0,2018-04-17,andres.lopez@technova.cl
12,14,Camila Vargas,35,Valparaíso,Soporte,800000.0,2021-10-02,camila.vargas@technova.cl
13,15,Sebastián Reyes,36,Concepción,Ventas,1050000.0,2020-01-28,sin_correo
14,16,Javiera Núñez,27,Santiago,Marketing,910000.0,2023-02-11,javiera.nunez@technova.cl
15,17,Matías Herrera,33,Antofagasta,Soporte,830000.0,2019-05-09,matias.herrera@technova.cl
16,18,Paula Morales,48,Antofagasta,Gerencia,2400000.0,2016-08-21,paula.morales@technova.cl